
general:
  db_name: test.db
  game_to_run: robots

games:
  robots:
    seed: 100
    gym_params:
      id: RobotsEnv-v0
      entry_point: fikuka_lakuka.gym.envs:RobotsEnv
      max_episode_steps: 500
    playing_agents:
      - random
      - random
    environment:
      gas_fee: 0.1
      grid_size: [10,10]
      rocks: [[2,2], [4,5], [3,3]]
      rocks_reward: [0, 1, 3]
      start: [0,0]
      end: [9,9]

agents:
  robots:
    PPOtest:
      name : PPOtest
    random:
      name: random



