
general:
  db_name: run_1
  game_to_run: robots2

games:
  robots:
    seed: 100
    gym_params:
      id: RobotsEnv-v0
      entry_point: fikuka_lakuka.gym.envs:RobotsEnv
      max_episode_steps: 100
    playing_agents:
      - random
      - bbu
    environment:
      sample_prob: 0.9
      gas_fee: 0.1
      grid_size: [10,10]
      rocks: [[2,2], [4,5], [3,3]]
      rocks_reward: [-10, 10, 10]
      start: [0,0]
      end: [9,9]
      starting_agent: 0

  robots2:
    seed: 101
    gym_params:
      id: RobotsEnv-v0
      entry_point: fikuka_lakuka.gym.envs:RobotsEnv
      max_episode_steps: 100
    playing_agents:
      - bbu
    environment:
      sample_prob: 0.9
      gas_fee: 0.1
      grid_size: [15,15]
      rocks: [[0,14], [1,14], [0,13], [12,0]]
      rocks_reward: [-15, -15, -15, 15]
      start: [0,0]
      end: [14,14]
      starting_agent: 0
  oracle:
    seed: 102
    gym_params:
      id: RobotsEnv-v0
      entry_point: fikuka_lakuka.gym.envs:RobotsEnv
      max_episode_steps: 100
    playing_agents:
      - random
      - bbu
    environment:
      sample_prob: 0.9
      gas_fee: 0.1
      grid_size: [15,15]
      rocks: [[2,2], [3,3], [4,5], [13,14]]
      rocks_reward: [-10, 10, 10, 10,-15]
      start: [0,0]
      end: [14,14]
      starting_agent: 0
agents:
  robots:
    PPOtest:
      name : PPOtest
    random:
      name: random
    algo:
      name: algo
    bbu:
      name: bbu

  robots2:
    PPOtest:
      name : PPOtest
    random:
      name: random
    algo:
      name: algo
    bbu:
      name: bbu
    manual:
      name: manual
    const:
      name: const
assets:

