
general:
  db_name: run_1
  game_to_run: robots


games:
  robots:
    seed: 100
    gym_params:
      id: RobotsEnv-v0
      entry_point: fikuka_lakuka.gym.envs:RobotsEnv
      max_episode_steps: 500
    playing_agents:
      - algo
      - random
    environment:
      sample_prob: 0.2
      gas_fee: 0.1
      grid_size: [10,10]
      rocks: [[2,2], [4,5], [3,3]]
      rocks_reward: [0, 10, 3]
      start: [0,0]
      end: [9,9]
      starting_agent: 0

agents:
  robots:
    PPOtest:
      name : PPOtest
    random:
      name: random
    algo:
      name: algo


assets:

